baseURL = 'blog.cameronengineer.com'
languageCode = 'en-us'
title = "Cameron's Note's"
theme = ["archie"]


[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'

[params]
	mode="auto"
  favicon = "/favicon.png"
  useCDN = false
  Description = "A personal blog sharing notes and insights on topics I care about â€” from engineering and cybersecurity to flying, cooking, and hiking."

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/cameronengineer/"

[[params.social]]
name = "GitHub"
icon = "github"
url  = "https://github.com/cameronengineer"

[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
name = "Flying"
url = "/tags/Flying"
weight = 2


[[menu.main]]
name = "Engineering"
url = "/tags/Engineering"
weight = 3


[services]
  [services.googleAnalytics]
    id = 'G-MSXT4PVT9B'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true